version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

    environment:
      - DB_NAME=dev.sqlite
      - SYNCHRONIZE=true
      - DB_TYPE=sqlite
      - LOGGING=true
    networks:
      - app
    depends_on:
      - database

  database:
    image: sqlite:latest
    container_name: sqlite_db
    volumes:
      - ./data:/data
    networks:
      - app

networks:
  app:
    driver: bridge
volumes:
  db-data:
